#!/usr/bin/env python3
"""Compile the tracking_country_hubs.sql file into a compact C header."""

from __future__ import annotations

import argparse
import sqlite3
from pathlib import Path
from typing import List, Tuple


DEFAULT_SQL = Path("data/tracking_country_hubs.sql")
DEFAULT_HEADER = Path("include/tracking_country_hubs.h")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate a header for country-level logistics hubs."
    )
    parser.add_argument(
        "--sql",
        type=Path,
        default=DEFAULT_SQL,
        help=f"Path to the SQL seed file (default: {DEFAULT_SQL})",
    )
    parser.add_argument(
        "--header",
        type=Path,
        default=DEFAULT_HEADER,
        help=f"Destination header path (default: {DEFAULT_HEADER})",
    )
    return parser.parse_args()


def load_hubs(sql_path: Path) -> List[Tuple[str, str, str, int]]:
    if not sql_path.exists():
        raise FileNotFoundError(f"SQL file not found: {sql_path}")
    conn = sqlite3.connect(":memory:")
    try:
        with sql_path.open("r", encoding="utf-8") as handle:
            conn.executescript(handle.read())
        rows = conn.execute(
            "SELECT iso_code, airport_code, airport_name, throughput_rank "
            "FROM tracking_country_hubs"
        ).fetchall()
    finally:
        conn.close()
    if not rows:
        raise ValueError("tracking_country_hubs table is empty")
    rows.sort(key=lambda item: (item[0], item[3], item[1]))
    return rows


def write_header(entries: List[Tuple[str, str, str, int]], destination: Path) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    with destination.open("w", encoding="utf-8") as handle:
        handle.write("// Auto-generated by scripts/generate_country_hubs_header.py\n")
        handle.write("#pragma once\n\n")
        handle.write("#include <stdint.h>\n\n")
        handle.write("typedef struct {\n")
        handle.write("    char iso[3];\n")
        handle.write("    char iata[4];\n")
        handle.write("    uint8_t priority;\n")
        handle.write("} tracking_country_hub_t;\n\n")
        handle.write(f"#define TRACKING_COUNTRY_HUB_COUNT {len(entries)}\n")
        handle.write("static const tracking_country_hub_t TRACKING_COUNTRY_HUBS[TRACKING_COUNTRY_HUB_COUNT] = {\n")
        for iso, iata, _name, priority in entries:
            handle.write(f"    {{\"{iso}\", \"{iata}\", {priority}}},\n")
        handle.write("};\n")


def main() -> int:
    args = parse_args()
    entries = load_hubs(args.sql)
    write_header(entries, args.header)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
