#!/usr/bin/env python3
"""Convert IMP code CSV/JSON files into a binary-search-friendly C header."""
from __future__ import annotations

import argparse
import csv
import json
import sys
from collections import Counter
from pathlib import Path
from typing import Iterable, List, Sequence


IMPC_FIELD = "impc_code"
IATA_FIELD = "iata_code"
LAT_FIELD = "latitude"
LON_FIELD = "longitude"
TZ_FIELD = "timezone_offset"
TZ_BIAS = 720  # bias to keep values within uint16_t for WASM-friendly layout


class InputError(ValueError):
    """Raised when the source data is malformed."""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Convert IMP logistics nodes from CSV/JSON into an aligned C header "
            "sorted for binary search."
        )
    )
    parser.add_argument(
        "input",
        type=Path,
        help="Path to the source CSV or JSON file containing IMP nodes.",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=Path("include/impc_data.h"),
        help="Destination header file. Defaults to include/impc_data.h.",
    )
    parser.add_argument(
        "-f",
        "--format",
        choices={"csv", "json"},
        help="Override input format detection (uses extension by default).",
    )
    return parser.parse_args()


def detect_format(path: Path, override: str | None) -> str:
    if override:
        return override
    suffix = path.suffix.lower()
    if suffix == ".csv":
        return "csv"
    if suffix == ".json":
        return "json"
    raise InputError(
        f"Unable to detect format from extension '{path.suffix}'. Use --format."
    )


def load_records(path: Path, fmt: str) -> List[dict]:
    if fmt == "csv":
        return list(_load_csv(path))
    return list(_load_json(path))


def _load_csv(path: Path) -> Iterable[dict]:
    with path.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        _validate_columns(reader.fieldnames)
        for row in reader:
            yield _normalize_row(row)


def _load_json(path: Path) -> Iterable[dict]:
    with path.open(encoding="utf-8") as handle:
        payload = json.load(handle)
    if isinstance(payload, dict):
        payload = payload.get("data") or payload.get("items") or payload.get("nodes")
    if not isinstance(payload, Sequence):
        raise InputError("JSON input must be a list or contain a 'data/items/nodes' list.")
    for row in payload:
        if not isinstance(row, dict):
            raise InputError("JSON entries must be objects.")
        yield _normalize_row(row)


def _validate_columns(columns: Sequence[str] | None) -> None:
    expected = {IMPC_FIELD, IATA_FIELD, LAT_FIELD, LON_FIELD, TZ_FIELD}
    if not columns or not expected.issubset(columns):
        raise InputError(
            "CSV must contain columns: impc_code, iata_code, latitude, "
            "longitude, timezone_offset"
        )


def _normalize_row(row: dict) -> dict:
    return {
        IMPC_FIELD: _normalize_str(row.get(IMPC_FIELD), IMPC_FIELD, 6),
        IATA_FIELD: _normalize_str(row.get(IATA_FIELD), IATA_FIELD, 3),
        LAT_FIELD: _normalize_float(row.get(LAT_FIELD), LAT_FIELD),
        LON_FIELD: _normalize_float(row.get(LON_FIELD), LON_FIELD),
        TZ_FIELD: _encode_tz(row.get(TZ_FIELD)),
    }


def _normalize_str(value, field: str, max_len: int) -> str:
    if value is None:
        raise InputError(f"Missing field '{field}'.")
    text = str(value).strip().upper()
    if not text:
        raise InputError(f"Field '{field}' cannot be empty.")
    if len(text) > max_len:
        raise InputError(f"Field '{field}' exceeds {max_len} characters: {text}")
    return text


def _normalize_float(value, field: str) -> float:
    if value is None:
        raise InputError(f"Missing field '{field}'.")
    try:
        return float(value)
    except (TypeError, ValueError) as exc:
        raise InputError(f"Invalid float for '{field}': {value}") from exc


def _encode_tz(value) -> int:
    if value is None:
        raise InputError("Missing field 'timezone_offset'.")
    try:
        offset = int(value)
    except (TypeError, ValueError) as exc:
        raise InputError(f"Invalid timezone offset: {value}") from exc
    encoded = offset + TZ_BIAS
    if not 0 <= encoded <= 0xFFFF:
        raise InputError(
            f"Encoded timezone '{encoded}' is out of uint16_t range. Original: {offset}"
        )
    return encoded


def format_float(value: float) -> str:
    text = f"{value:.6f}".rstrip("0").rstrip(".")
    return (text or "0") + "f"


def write_header(records: Sequence[dict], destination: Path) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "// Generated by scripts/generate_impc_header.py -- do not edit.",
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        "typedef struct {",
        "    char impc[7];",
        "    char iata[4];",
        "    float lat;",
        "    float lon;",
        "    uint16_t tz_offset;",
        "} impc_mapping_t;",
        "",
        f"#define IMPC_TABLE_SIZE {len(records)}",
        "static const impc_mapping_t IMPC_TABLE[IMPC_TABLE_SIZE] = {",
    ]
    for entry in records:
        lines.append(
            "    {\"%s\", \"%s\", %s, %s, %d},"
            % (
                entry[IMPC_FIELD],
                entry[IATA_FIELD],
                format_float(entry[LAT_FIELD]),
                format_float(entry[LON_FIELD]),
                entry[TZ_FIELD],
            )
        )
    lines.append("};")
    lines.append("")
    destination.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    args = parse_args()
    try:
        fmt = detect_format(args.input, args.format)
        records = load_records(args.input, fmt)
    except InputError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    records.sort(key=lambda item: item[IMPC_FIELD])
    duplicates = [code for code, count in Counter(r[IMPC_FIELD] for r in records).items() if count > 1]
    if duplicates:
        dup_list = ", ".join(sorted(duplicates))
        print(f"warning: duplicate impc_code entries detected -> {dup_list}", file=sys.stderr)

    write_header(records, args.output)
    print(f"Wrote {len(records)} entries to {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
