// Generated by scripts/generate_impc_header.py -- do not edit.
#pragma once

#include <stdint.h>

typedef struct {
    char impc[7];
    char iata[4];
    float lat;
    float lon;
    uint16_t tz_offset;
} impc_mapping_t;

#define IMPC_TABLE_SIZE 34
static const impc_mapping_t IMPC_TABLE[IMPC_TABLE_SIZE] = {
    {"AEDXBA", "DXB", 25.2532f, 55.3657f, 960},
    {"AUMELA", "MEL", -37.669f, 144.841f, 1320},
    {"AUSYDA", "SYD", -33.9399f, 151.1753f, 1320},
    {"BRGRUA", "GRU", -23.4356f, -46.4731f, 540},
    {"BRRJAA", "GIG", -22.809f, -43.25f, 540},
    {"CAYTOA", "YYZ", 43.6777f, -79.6248f, 420},
    {"CAYVRA", "YVR", 49.1967f, -123.1815f, 240},
    {"CNBJSA", "PEK", 40.0801f, 116.5846f, 1200},
    {"CNGUAA", "CAN", 23.3924f, 113.2988f, 1200},
    {"CNPVGA", "PVG", 31.1443f, 121.8083f, 1200},
    {"DEFRAB", "FRA", 50.0379f, 8.5622f, 780},
    {"ESMADA", "MAD", 40.4983f, -3.5676f, 780},
    {"FRPARA", "CDG", 49.0097f, 2.5479f, 780},
    {"GBLONA", "LHR", 51.47f, -0.4543f, 720},
    {"HKHKGA", "HKG", 22.308f, 113.9185f, 1200},
    {"HUBUDA", "BUD", 47.4369f, 19.2556f, 780},
    {"INDELA", "DEL", 28.5562f, 77.1f, 1050},
    {"ITROMA", "FCO", 41.8003f, 12.2389f, 780},
    {"JPOSAA", "KIX", 34.7855f, 135.4382f, 1260},
    {"JPTYOA", "NRT", 35.7719f, 140.3929f, 1260},
    {"KRSELA", "ICN", 37.4602f, 126.4407f, 1260},
    {"KRSELB", "ICN", 37.4602f, 126.4407f, 1260},
    {"NLAMSA", "AMS", 52.3105f, 4.7683f, 780},
    {"QADOHA", "DOH", 25.2731f, 51.6081f, 900},
    {"SGSINA", "SIN", 1.3644f, 103.9915f, 1200},
    {"THBKKA", "BKK", 13.69f, 100.7501f, 1140},
    {"TRISTA", "IST", 41.2753f, 28.7519f, 900},
    {"USCHIA", "ORD", 41.9742f, -87.9073f, 360},
    {"USLAXA", "LAX", 33.9416f, -118.4085f, 240},
    {"USMIAA", "MIA", 25.7959f, -80.287f, 420},
    {"USNYCA", "JFK", 40.6413f, -73.7781f, 420},
    {"USSEAA", "SEA", 47.4502f, -122.3088f, 240},
    {"USSNFA", "SFO", 37.6213f, -122.379f, 240},
    {"ZAJNBA", "JNB", -26.1367f, 28.242f, 840},
};
