// Auto-generated by scripts/generate_country_hubs_header.py
#pragma once

#include <stdint.h>

typedef struct {
    char iso[3];
    char iata[4];
    uint8_t priority;
} tracking_country_hub_t;

#define TRACKING_COUNTRY_HUB_COUNT 30
static const tracking_country_hub_t TRACKING_COUNTRY_HUBS[TRACKING_COUNTRY_HUB_COUNT] = {
    {"AE", "DXB", 1},
    {"AU", "SYD", 1},
    {"BR", "GRU", 1},
    {"CA", "YYZ", 1},
    {"CL", "SCL", 1},
    {"CN", "PVG", 1},
    {"DE", "FRA", 1},
    {"ES", "MAD", 1},
    {"FI", "HEL", 1},
    {"FR", "CDG", 1},
    {"GB", "LHR", 1},
    {"HK", "HKG", 1},
    {"IN", "DEL", 1},
    {"IT", "FCO", 1},
    {"JP", "NRT", 1},
    {"KR", "ICN", 1},
    {"MX", "MEX", 1},
    {"MY", "KUL", 1},
    {"NL", "AMS", 1},
    {"PH", "MNL", 1},
    {"QA", "DOH", 1},
    {"RU", "SVO", 1},
    {"SA", "RUH", 1},
    {"SE", "ARN", 1},
    {"SG", "SIN", 1},
    {"TH", "BKK", 1},
    {"TR", "IST", 1},
    {"US", "JFK", 1},
    {"VN", "SGN", 1},
    {"ZA", "JNB", 1},
};
